const events = [
  {id:1,date:'2026-08-01',title:'第58回 紀州おどり「ぶんだら節」',city:'和歌山市',category:'お祭り',time:'18:15〜20:30',place:'和歌山城周辺',free:true,kids:true,description:'和歌山の夏を彩る市民参加型の踊りイベントです。',source:'和歌山市観光課 Instagram',sourceUrl:'https://www.instagram.com/wakayamacity.kanko/'},
  {id:2,date:'2026-08-01',title:'城前ひろばマルシェ',city:'和歌山市',category:'マルシェ',time:'15:00〜22:00',place:'和歌山城 城前ひろば',free:true,kids:true,description:'飲食や雑貨などが集まる、夏のナイトマルシェです。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/shiromae_hiroba_marche/'},
  {id:4,date:'2026-08-07',title:'kokomo SUNSET MARKET',city:'和歌山市',category:'マルシェ',time:'16:00〜20:30',place:'和歌山市駅前広場',free:true,kids:true,description:'金曜夕方の市駅前に、飲食や物販のお店が集まります。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/officekokomo/'},
  {id:5,date:'2026-08-08',title:'貴志駅神戸盆祭',city:'紀の川市',category:'お祭り',time:'15:30〜20:30',place:'貴志駅前',free:true,kids:true,description:'貴志駅前で行われる、地域の盆祭りとマルシェです。',source:'ATTO! KINOKAWA MARCHE Instagram',sourceUrl:'https://www.instagram.com/attomarche/'},
  {id:6,date:'2026-08-09',title:'てとこと市',city:'和歌山市',category:'マルシェ',time:'16:00〜21:00',place:'本町公園',free:true,kids:true,description:'グルメ、雑貨、ワークショップ、子ども向け縁日などが並ぶ夜市です。',source:'てとこと市 公式Instagram',sourceUrl:'https://www.instagram.com/tetocotoichi/'},
  {id:7,date:'2026-08-10',title:'みその夜市 2026 SUMMER',city:'和歌山市',category:'お祭り',time:'17:00〜22:00',place:'みその商店街',free:true,kids:true,description:'商店街で楽しむ夏の夜市です。店舗や屋台の情報は公式投稿をご確認ください。',source:'みそのマルシェ 公式Instagram',sourceUrl:'https://www.instagram.com/misono.marche/'},
  {id:8,date:'2026-08-11',title:'浜のうたせ SEASIDE MARCHE',city:'有田市',category:'マルシェ',time:'10:00〜15:30',place:'新鮮市場 浜のうたせ',free:true,kids:true,description:'海辺の市場にフードやハンドメイドのお店が集まるマルシェです。',source:'浜のうたせ 公式Instagram',sourceUrl:'https://www.instagram.com/hamanoutase/'},
  {id:9,date:'2026-08-13',title:'ふるさと海南まつり',city:'海南市',category:'お祭り',time:'開催時間は公式情報を確認',place:'海南市内',free:true,kids:true,description:'ステージや出店で海南の夏を盛り上げる恒例のお祭りです。',source:'海南市公式サイト',sourceUrl:'https://www.city.kainan.lg.jp/'},
  {id:10,date:'2026-08-14',title:'kokomo SUNSET MARKET',city:'和歌山市',category:'マルシェ',time:'16:00〜20:30',place:'和歌山市駅前広場',free:true,kids:true,description:'金曜夕方の市駅前に、飲食や物販のお店が集まります。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/officekokomo/'},
  {id:11,date:'2026-08-15',title:'浜のうたせ SEASIDE MARCHE',city:'有田市',category:'マルシェ',time:'10:00〜15:30',place:'新鮮市場 浜のうたせ',free:true,kids:true,description:'海辺の市場にフードやハンドメイドのお店が集まるマルシェです。',source:'浜のうたせ 公式Instagram',sourceUrl:'https://www.instagram.com/hamanoutase/'},
  {id:12,date:'2026-08-15',title:'マルシェインノビノス',city:'海南市',category:'マルシェ',time:'10:00〜16:00',place:'海南nobinos',free:true,kids:true,description:'個性豊かなお店や作り手が集まる屋内マルシェです。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/shurin1038/'},
  {id:13,date:'2026-08-15',title:'百鬼盆祭り',city:'和歌山市',category:'お祭り',time:'16:00〜21:00',place:'北ぶらくり丁商店街',free:true,kids:true,description:'妖怪をテーマに、グルメや雑貨、仮装を楽しむナイトマルシェです。',source:'北ぶらリメンバーマーケット Instagram',sourceUrl:'https://www.instagram.com/kitabura_remarket/'},
  {id:14,date:'2026-08-16',title:'つどいの実マルシェ',city:'紀の川市',category:'マルシェ',time:'17:00〜21:00',place:'MIKASAKAN',free:true,kids:true,description:'店舗・作り手と地域の人が集う夕方開催のマルシェです。',source:'MIKASAKAN 公式Instagram',sourceUrl:'https://www.instagram.com/mikasakan.kokawa/'},
  {id:15,date:'2026-08-17',title:'みそのマルシェ',city:'和歌山市',category:'マルシェ',time:'11:00〜16:00',place:'みその商店街',free:true,kids:true,description:'商店街に地域のお店が集まる昼のマルシェです。',source:'みそのマルシェ 公式Instagram',sourceUrl:'https://www.instagram.com/misono.marche/'},
  {id:16,date:'2026-08-21',title:'kokomo SUNSET MARKET',city:'和歌山市',category:'マルシェ',time:'16:00〜20:30',place:'和歌山市駅前広場',free:true,kids:true,description:'金曜夕方の市駅前に、飲食や物販のお店が集まります。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/officekokomo/'},
  {id:17,date:'2026-08-21',title:'KAINAN NIGHT MARKET',city:'海南市',category:'マルシェ',time:'16:00〜21:00',place:'中西農園',free:true,kids:true,description:'農園を会場に開催される海南のナイトマーケットです。',source:'まるまち掲載・主催者情報',sourceUrl:'https://marumachi.org/prefectures/wakayama'},
  {id:19,date:'2026-08-25',title:'わかやま癒されフェスタ vol.12',city:'和歌山市',category:'美容・健康',time:'公式情報を確認',place:'和歌山市内',free:false,kids:false,description:'地域のお店やセラピストが参加する、癒しをテーマにしたイベントです。',source:'まいぷれ和歌山',sourceUrl:'https://wakayama.mypl.net/event/'},
  {id:20,date:'2026-08-28',title:'kokomo SUNSET MARKET',city:'和歌山市',category:'マルシェ',time:'16:00〜20:30',place:'和歌山市駅前広場',free:true,kids:true,description:'金曜夕方の市駅前に、飲食や物販のお店が集まります。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/officekokomo/'},
  {id:21,date:'2026-08-29',title:'親子で作る動物レザークラフト体験',city:'和歌山市',category:'ワークショップ',time:'公式情報を確認',place:'和歌山城公園動物園',free:false,kids:true,description:'夏休みに親子で楽しめる動物レザークラフトのワークショップです。',source:'史跡 和歌山城 公式サイト',sourceUrl:'https://wakayamajo.jp/official-event/1475/'},
  {id:22,date:'2026-08-29',title:'夢叶キラキラマルシェ',city:'和歌山市',category:'ワークショップ',time:'10:00〜17:00',place:'和歌山城ホール',free:true,kids:true,description:'体験型ワークショップなどを通して「好き」と出会うイベントです。',source:'エフエム和歌山',sourceUrl:'https://877.fm/information.php?id=890'},
  {id:23,date:'2026-08-30',title:'紀州よさこい夏まつり',city:'和歌山市',category:'お祭り',time:'16:00〜21:00',place:'和歌山城 西の丸広場',free:true,kids:true,description:'踊り子たちが和歌山の夏を盛り上げる、よさこいイベントです。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/odorunya_wakayama/'},
  {id:24,date:'2026-08-30',title:'城前ひろばナイトマルシェ',city:'和歌山市',category:'マルシェ',time:'15:00〜21:00',place:'和歌山城 城前ひろば',free:true,kids:true,description:'飲食や雑貨などが集まる城前ひろばのナイトマルシェです。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/shiromae_hiroba_marche/'},
  {id:25,date:'2026-09-04',title:'kokomo SUNSET MARKET（9月開催候補）',city:'和歌山市',category:'マルシェ',time:'日時要確認',place:'和歌山市駅前広場',free:true,kids:true,unconfirmed:true,description:'市駅前で継続開催されている夕方のマーケットです。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/officekokomo/'},
  {id:26,date:'2026-09-05',title:'826aska Live Tour 2026',city:'和歌山市',category:'音楽・舞台',time:'13:30〜／16:30〜',place:'和歌山 CLUB GATE',free:false,kids:false,description:'エレクトーン奏者826askaのライブ公演です。',source:'イープラス和歌山',sourceUrl:'https://eplus.jp/sf/live/kansai/wakayama'},
  {id:27,date:'2026-09-11',title:'kokomo SUNSET MARKET（9月開催候補）',city:'和歌山市',category:'マルシェ',time:'日時要確認',place:'和歌山市駅前広場',free:true,kids:true,unconfirmed:true,description:'市駅前で継続開催されている夕方のマーケットです。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/officekokomo/'},
  {id:28,date:'2026-09-13',title:'てとこと市（9月開催候補）',city:'和歌山市',category:'マルシェ',time:'日時要確認',place:'本町公園',free:true,kids:true,unconfirmed:true,description:'毎月開催されている、グルメ・雑貨・体験が集まるマーケットです。',source:'てとこと市 公式Instagram',sourceUrl:'https://www.instagram.com/tetocotoichi/'},
  {id:29,date:'2026-09-18',title:'kokomo SUNSET MARKET（9月開催候補）',city:'和歌山市',category:'マルシェ',time:'日時要確認',place:'和歌山市駅前広場',free:true,kids:true,unconfirmed:true,description:'市駅前で継続開催されている夕方のマーケットです。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/officekokomo/'},
  {id:30,date:'2026-09-20',title:'押尾コータロー アコースティックギターライブ',city:'和歌山市',category:'音楽・舞台',time:'17:00〜',place:'和歌山オールドタイム',free:false,kids:false,description:'押尾コータローによるアコースティックギターライブです。',source:'イープラス和歌山',sourceUrl:'https://eplus.jp/sf/live/kansai/wakayama'},
  {id:31,date:'2026-09-21',title:'TENDOUJI LIVE',city:'和歌山市',category:'音楽・舞台',time:'17:00〜',place:'和歌山オールドタイム',free:false,kids:false,description:'ロックバンドTENDOUJIの和歌山公演です。',source:'イープラス和歌山',sourceUrl:'https://eplus.jp/sf/live/kansai/wakayama'},
  {id:32,date:'2026-09-25',title:'kokomo SUNSET MARKET（9月開催候補）',city:'和歌山市',category:'マルシェ',time:'日時要確認',place:'和歌山市駅前広場',free:true,kids:true,unconfirmed:true,description:'市駅前で継続開催されている夕方のマーケットです。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/officekokomo/'},
  {id:33,date:'2026-09-27',title:'SEASIDE BBQ & BEER GARDEN',city:'和歌山市',category:'グルメ',time:'営業時間は公式情報を確認',place:'和歌山市内',free:false,kids:true,unconfirmed:true,description:'夏から秋にかけて開催される期間限定のビアガーデンです。',source:'まいぷれ和歌山',sourceUrl:'https://wakayama.mypl.net/event/'},
  {id:34,date:'2026-10-02',title:'女性の就職応援フェア2026',city:'和歌山市',category:'暮らし',time:'日時要確認',place:'和歌山ビッグ愛',free:true,kids:false,description:'これから働くことを希望する子育て中の女性などを対象とした就職イベントです。',source:'和歌山県 就職イベント情報',sourceUrl:'https://www.wakayama-uiturn.jp/'},
  {id:35,date:'2026-10-03',title:'スターダスト☆レビュー コンサート',city:'和歌山市',category:'音楽・舞台',time:'17:00〜',place:'和歌山県民文化会館 大ホール',free:false,kids:false,description:'スターダスト☆レビューの和歌山公演です。',source:'イープラス和歌山',sourceUrl:'https://eplus.jp/sf/event/month-10/kansai/wakayama'},
  {id:36,date:'2026-10-04',title:'城前ひろばマルシェ（10月開催候補）',city:'和歌山市',category:'マルシェ',time:'日時要確認',place:'和歌山城 城前ひろば',free:true,kids:true,unconfirmed:true,description:'和歌山城前に飲食や雑貨のお店が集まる定期マルシェです。',source:'主催者公式Instagram',sourceUrl:'https://www.instagram.com/shiromae_hiroba_marche/'},
  {id:37,date:'2026-10-07',title:'障がい者就職面接会',city:'和歌山市',category:'暮らし',time:'日時要確認',place:'和歌山ビッグ愛',free:true,kids:false,description:'障害のある方を対象とした就職面接会です。',source:'和歌山県 就職イベント情報',sourceUrl:'https://www.wakayama-uiturn.jp/'},
  {id:38,date:'2026-10-11',title:'ウインズ平阪40周年ライブ in 和歌山',city:'和歌山市',category:'音楽・舞台',time:'17:00〜',place:'SHELTER',free:false,kids:false,description:'ウインズ平阪の40周年を記念する和歌山ライブです。',source:'イープラス和歌山',sourceUrl:'https://eplus.jp/sf/live/kansai/wakayama'},
  {id:39,date:'2026-10-11',title:'てとこと市（10月開催候補）',city:'和歌山市',category:'マルシェ',time:'日時要確認',place:'本町公園',free:true,kids:true,unconfirmed:true,description:'毎月開催されている、グルメ・雑貨・体験が集まるマーケットです。',source:'てとこと市 公式Instagram',sourceUrl:'https://www.instagram.com/tetocotoichi/'},
  {id:40,date:'2026-10-18',title:'ティラノサウルスレース関連イベント',city:'海南市',category:'スポーツ',time:'9:00〜12:00頃',place:'開催場所は公式情報を確認',free:false,kids:true,unconfirmed:true,description:'親子でも楽しめる体験型スポーツイベントの開催情報です。',source:'和歌山県公式観光サイト',sourceUrl:'https://www.wakayama-kanko.or.jp/events/index_3_1______.html'},
  {id:41,date:'2026-10-25',title:'岩出・紀の川就職フェア',city:'紀の川市',category:'暮らし',time:'日時要確認',place:'粉河ふるさとセンター',free:true,kids:false,description:'岩出・紀の川地域の企業と出会える合同就職イベントです。',source:'和歌山県 就職イベント情報',sourceUrl:'https://www.wakayama-uiturn.jp/'},
  {id:42,date:'2026-10-27',title:'ミニ合同企業説明会',city:'和歌山市',category:'暮らし',time:'日時要確認',place:'和歌山城ホール',free:true,kids:false,description:'新卒者などを対象とした小規模な合同企業説明会です。',source:'和歌山県 就職イベント情報',sourceUrl:'https://www.wakayama-uiturn.jp/'},
  {id:43,date:'2026-08-21',title:'JURASSIC WORLD THE VILLAINS POP UP SHOP',city:'和歌山市',category:'商業施設',time:'8月30日まで・営業時間内',place:'イオンモール和歌山',free:true,kids:true,description:'映画「ジュラシック・ワールド」の期間限定ポップアップショップです。',source:'イオンモール和歌山',sourceUrl:'https://wakayama.aeonmall.jp/lp/202606lp/'},
  {id:44,date:'2026-08-22',title:'カインズサンセットマルシェ',city:'和歌山市',category:'マルシェ',time:'日時要確認',place:'カインズ和歌山店周辺',free:true,kids:true,unconfirmed:true,description:'地域のお店や作り手が集まる夕方開催のマルシェです。',source:'まいぷれ和歌山',sourceUrl:'https://wakayama.mypl.net/event/'},
  {id:45,date:'2026-08-23',title:'和歌山県立近代美術館 紀陽文化財団の日',city:'和歌山市',category:'文化・芸術',time:'開館時間内',place:'和歌山県立近代美術館',free:false,kids:true,description:'大学生の観覧が無料になる美術館の特別日です。開催中の展覧会も楽しめます。',source:'和歌山県立近代美術館',sourceUrl:'https://www.momaw.jp/exhibit/'},
  {id:46,date:'2026-09-04',title:'ママハピEXPO',city:'和歌山市',category:'子育て',time:'日時要確認',place:'イオンモール和歌山',free:true,kids:true,description:'親子で楽しめる体験や地域のお店・サービスに出会える子育てイベントです。',source:'イオンモール和歌山',sourceUrl:'https://wakayama.aeonmall.jp/event'},
  {id:47,date:'2026-09-07',title:'和歌山県立近代美術館 無料入館日',city:'和歌山市',category:'文化・芸術',time:'開館時間内',place:'和歌山県立近代美術館',free:true,kids:true,description:'毎月第1日曜日を中心に実施される無料入館日です。',source:'和歌山県立近代美術館',sourceUrl:'https://www.momaw.jp/exhibit/'},
  {id:48,date:'2026-09-14',title:'岩出市 地域子育て支援センターイベント',city:'岩出市',category:'子育て',time:'日時要確認',place:'岩出市内 子育て支援施設',free:true,kids:true,unconfirmed:true,description:'未就園児を対象に、季節の製作やふれあい遊びを行う親子イベントです。',source:'岩出市イベントカレンダー',sourceUrl:'https://www.city.iwade.lg.jp/calendar/'},
  {id:49,date:'2026-10-05',title:'和歌山県立近代美術館 無料入館日',city:'和歌山市',category:'文化・芸術',time:'開館時間内',place:'和歌山県立近代美術館',free:true,kids:true,description:'毎月第1日曜日を中心に実施される無料入館日です。',source:'和歌山県立近代美術館',sourceUrl:'https://www.momaw.jp/exhibit/'},
  {id:50,date:'2026-09-20',title:'ビッグホエール スポーツ・催事情報',city:'和歌山市',category:'施設イベント',time:'日時要確認',place:'和歌山ビッグホエール',free:false,kids:true,unconfirmed:true,description:'スポーツ大会や展示催事など、ビッグホエールの月間開催候補です。',source:'和歌山ビッグホエール公式行事予定',sourceUrl:'https://www.wakayamasposhin.or.jp/big-whale/event/'},
  {id:51,date:'2026-09-26',title:'道の駅 季節の収穫・販売イベント',city:'紀の川市',category:'道の駅・市場',time:'日時要確認',place:'道の駅 青洲の里',free:true,kids:true,unconfirmed:true,description:'旬の農産物販売や地域企画を検索対象として掲載しています。',source:'施設・観光公式情報',sourceUrl:'https://www.city.kinokawa.lg.jp/'},
  {id:52,date:'2026-10-10',title:'市発信の親子向け遊び・交流イベント',city:'和歌山市',category:'子育て',time:'日時要確認',place:'和歌山市内の子育て支援施設・遊び場',free:true,kids:true,unconfirmed:true,description:'市の子育て支援施設で行われる親子交流、読み聞かせ、遊びの企画です。',source:'和歌山市公式サイト',sourceUrl:'https://www.city.wakayama.wakayama.jp/'},
  {id:53,date:'2026-10-17',title:'海南市 子育てひろばイベント',city:'海南市',category:'子育て',time:'日時要確認',place:'海南nobinosほか',free:true,kids:true,unconfirmed:true,description:'親子の遊びや読み聞かせなど、市内施設の子育て企画です。',source:'海南市公式サイト',sourceUrl:'https://www.city.kainan.lg.jp/'},
  {id:54,date:'2026-10-24',title:'有田市 親子で遊べる地域イベント',city:'有田市',category:'子育て',time:'日時要確認',place:'有田市内の子育て支援施設',free:true,kids:true,unconfirmed:true,description:'市や地域施設が発信する親子向けイベントの掲載候補です。',source:'有田市公式サイト',sourceUrl:'https://www.city.arida.lg.jp/event_calendar.html'},
  {id:55,date:'2026-08-03',title:'激辛めぐり！SUMMER2026',city:'岩出市',category:'グルメ',time:'9月30日まで',place:'岩出市内の参加飲食店',free:false,kids:false,description:'市内飲食店を巡り、それぞれの激辛メニューを楽しむ期間限定企画です。',source:'岩出市イベントカレンダー',sourceUrl:'https://www.city.iwade.lg.jp/calendar/'},
  {id:56,date:'2026-08-06',title:'みんな あつまれ いわでっ子！',city:'岩出市',category:'子育て',time:'10:30〜11:30',place:'岩出市総合保健福祉センター',free:true,kids:true,description:'未就園児を対象に、季節の製作やふれあい遊びを楽しむ親子イベントです。',source:'岩出市イベントカレンダー',sourceUrl:'https://www.city.iwade.lg.jp/calendar/'},
  {id:57,date:'2026-08-10',title:'岩出市 出前保育',city:'岩出市',category:'子育て',time:'10:00〜11:30',place:'市内公民館・岩出図書館',free:true,kids:true,description:'子育て支援センターの保育士が地域へ出向いて遊びの場を提供します。',source:'岩出市イベントカレンダー',sourceUrl:'https://www.city.iwade.lg.jp/calendar/'},
  {id:58,date:'2026-08-15',title:'日本代表選手と楽しむ ベースボール5体験教室',city:'岩出市',category:'スポーツ',time:'14:00〜16:00',place:'岩出市立市民総合体育館',free:false,kids:true,description:'岩出市制施行20周年を記念した、日本代表選手との体験教室です。',source:'岩出市イベントカレンダー',sourceUrl:'https://www.city.iwade.lg.jp/calendar/'},
  {id:59,date:'2026-08-20',title:'紀の川市 期間限定屋内遊び場',city:'紀の川市',category:'子育て',time:'日時要確認',place:'紀の川市内',free:true,kids:true,unconfirmed:true,description:'暑い時期にも親子で遊べる、市発信の期間限定屋内遊び場です。',source:'紀の川市イベント・募集一覧',sourceUrl:'https://www.city.kinokawa.lg.jp/info.html'},
  {id:60,date:'2026-09-12',title:'紀の川市 子育てひろば「いっしょにあそぼ！」',city:'紀の川市',category:'子育て',time:'日時要確認',place:'紀の川市内',free:true,kids:true,unconfirmed:true,description:'親子の遊びや交流を楽しむ、市発信の子育てひろばです。',source:'紀の川市イベント・募集一覧',sourceUrl:'https://www.city.kinokawa.lg.jp/info.html'},
  {id:61,date:'2026-10-18',title:'青洲まつり2026',city:'紀の川市',category:'お祭り',time:'日時要確認',place:'青洲の里周辺',free:true,kids:true,unconfirmed:true,description:'華岡青洲を顕彰し、時代行列などを楽しむ紀の川市の地域イベントです。',source:'紀の川市イベント・募集一覧',sourceUrl:'https://www.city.kinokawa.lg.jp/info.html'},
  {id:62,date:'2026-08-03',title:'有田市郷土資料館 特別展',city:'有田市',category:'文化・芸術',time:'開館時間内',place:'有田市郷土資料館',free:false,kids:true,unconfirmed:true,description:'有田の歴史や文化にふれる郷土資料館の特別展です。',source:'有田市公式サイト',sourceUrl:'https://www.city.arida.lg.jp/'},
  {id:63,date:'2026-08-20',title:'スプラッシュBEAT～ずぶ濡れ大作戦！～',city:'和歌山市',category:'施設イベント',time:'開催時間は公式情報を確認',place:'ポルトヨーロッパ',free:false,kids:true,description:'音楽と水しぶきで盛り上がる、夏の体験型エンターテインメントです。',source:'和歌山マリーナシティ公式',sourceUrl:'https://www.marinacity.com/marinacity/'},
  {id:64,date:'2026-08-21',title:'ポルトヨーロッパ Bubble Show',city:'和歌山市',category:'施設イベント',time:'開催時間は公式情報を確認',place:'ポルトヨーロッパ',free:false,kids:true,unconfirmed:true,description:'家族で楽しめるシャボン玉のパフォーマンスショーです。',source:'和歌山マリーナシティ公式',sourceUrl:'https://www.marinacity.com/marinacity/'},
  {id:65,date:'2026-08-22',title:'黒潮市場 生マグロの解体ショー',city:'和歌山市',category:'グルメ',time:'毎日開催・時間要確認',place:'黒潮市場',free:true,kids:true,description:'職人が大きなマグロを目の前でさばく、黒潮市場の名物イベントです。',source:'和歌山マリーナシティ公式',sourceUrl:'https://www.marinacity.com/marinacity/'},
  {id:66,date:'2026-09-20',title:'和歌山マリーナシティ 花火イベント',city:'和歌山市',category:'お祭り',time:'19:30頃〜・要確認',place:'和歌山マリーナシティ',free:false,kids:true,unconfirmed:true,description:'音楽と花火を楽しめるマリーナシティのナイトイベントです。',source:'和歌山マリーナシティ公式',sourceUrl:'https://www.marinacity.com/marinacity/'},
  {id:67,date:'2026-10-03',title:'和歌山マリーナシティ 花火イベント',city:'和歌山市',category:'お祭り',time:'20:00頃〜・要確認',place:'和歌山マリーナシティ',free:false,kids:true,unconfirmed:true,description:'秋の夜空を彩るマリーナシティの花火イベントです。',source:'和歌山マリーナシティ公式',sourceUrl:'https://www.marinacity.com/marinacity/'},
  {id:68,date:'2026-09-09',title:'和歌山市 子育てイベント情報',city:'和歌山市',category:'子育て',time:'各イベントの案内を確認',place:'和歌山市内の各施設',free:true,kids:true,unconfirmed:true,description:'和歌山市が発信する親子向け講座、交流、健康、遊びなどのイベント情報です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:69,date:'2026-09-01',title:'マインクラフトで学ぶ プログラミング体験',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'マインクラフトを題材に、子どもが楽しくプログラミングを体験するイベントです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1067914.html'},
  {id:70,date:'2026-09-03',title:'英語絵本おはなし会',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'親子で英語の音やリズムと絵本を楽しむおはなし会です。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1009071.html'},
  {id:71,date:'2026-09-05',title:'きいちごのおはなし会',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'子どもと一緒に絵本やお話を楽しめる図書館イベントです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1066934.html'},
  {id:72,date:'2026-09-07',title:'親子ふれあいリトミック',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'音楽に合わせて親子で体を動かし、ふれあいを楽しむイベントです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1045354.html'},
  {id:73,date:'2026-09-09',title:'親と子のおりがみ教室',city:'和歌山市',category:'ワークショップ',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'親子で一緒に季節の折り紙作品を作る体験教室です。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1045342.html'},
  {id:74,date:'2026-09-11',title:'おきにいりの本をさがそう！～親子で本の宝さがし～',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'親子で図書館を巡り、お気に入りの一冊を探す読書イベントです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1068591.html'},
  {id:75,date:'2026-09-13',title:'ひらめきラボ～遊びながら学ぼう！～',city:'和歌山市',category:'学び・講座',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'遊びや実験を通じて子どもの好奇心を育てる学びイベントです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1031717.html'},
  {id:76,date:'2026-09-15',title:'ワクワクみんなのおはなし会',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'家族で絵本や物語を楽しめる、子ども向けのおはなし会です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:77,date:'2026-09-17',title:'親子天体観測会～夏の大三角を探そう！～',city:'和歌山市',category:'自然・アウトドア',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'親子で夜空を観察し、夏の大三角などの星を探す体験イベントです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1034747.html'},
  {id:78,date:'2026-09-19',title:'赤ちゃんのココロがわかる 親子で楽しむベビーサイン',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'赤ちゃんとのコミュニケーションに役立つベビーサインを親子で体験します。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1041587.html'},
  {id:79,date:'2026-09-21',title:'親子ふれあいリトミック（西分館）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'音楽と動きを通して、親子のふれあいを楽しむリトミックです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1059806.html'},
  {id:80,date:'2026-09-23',title:'English Storytime＆Play ～えいごであそぼう～',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'英語のお話と遊びを親子で気軽に楽しむ図書館イベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:81,date:'2026-08-04',title:'子育てひろば（8月開催分）',city:'和歌山市',category:'子育て',time:'10:00〜11:30',place:'市内コミュニティセンター',free:true,kids:true,description:'手遊び、ふれあい遊び、お話、おもちゃ作りなどを行う未就園児向けの広場です。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1012045.html'},
  {id:82,date:'2026-08-08',title:'子育てひろば パパとあそぼう',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市内',free:true,kids:true,unconfirmed:true,description:'父親と子どもが一緒に遊び、ふれあいを楽しむ子育てひろばです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1030087.html'},
  {id:83,date:'2026-08-12',title:'親と子のおりがみ教室（8月）',city:'和歌山市',category:'ワークショップ',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'親子で季節の折り紙作品を作る体験教室です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:84,date:'2026-08-13',title:'語りの森のむかしばなし・わらべうた（8月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'昔話とわらべうたを親子で楽しむおはなしイベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:85,date:'2026-08-14',title:'すくすく赤ちゃんおはなし会（8月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'赤ちゃんと保護者が絵本や読み聞かせを楽しむおはなし会です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:86,date:'2026-08-16',title:'絵本・紙芝居を楽しむ会（8月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'子どもと一緒に絵本や紙芝居を楽しむ会です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:87,date:'2026-08-17',title:'ひらめきラボ／遊びながら学ぼう！（8月）',city:'和歌山市',category:'学び・講座',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'遊びや実験を通して子どもの好奇心を育てるイベントです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1033085.html'},
  {id:88,date:'2026-08-18',title:'オリジナル化石づくり',city:'和歌山市',category:'ワークショップ',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'自分だけの化石模型を作って楽しむ子ども向け体験です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:89,date:'2026-08-19',title:'ワクワクみんなのおはなし会（8月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'家族で物語や絵本を楽しむおはなし会です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:90,date:'2026-08-21',title:'子育てひろば ☆おたのしみDAY',city:'和歌山市',category:'子育て',time:'10:00〜11:30',place:'紀の国住宅南コミュニティセンター',free:true,kids:true,description:'手遊びやふれあい遊び、おもちゃ作りを楽しむ特別な子育てひろばです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1009025.html'},
  {id:91,date:'2026-08-24',title:'赤ちゃんおはなし会（西分館・8月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'赤ちゃんと保護者のための読み聞かせイベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:92,date:'2026-08-26',title:'みんなのおはなし会（西分館・8月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'西分館で家族みんなが楽しめるおはなし会です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:93,date:'2026-08-28',title:'親子で楽しむベビーサイン（西分館・8月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'赤ちゃんとのコミュニケーションに役立つベビーサインを体験します。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:94,date:'2026-09-06',title:'おはなしだいすきよっといで！（9月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'子どもが絵本や物語に親しめるおはなし会です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:95,date:'2026-09-08',title:'語りの森のむかしばなし・わらべうた（9月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'昔話とわらべうたを親子で楽しむイベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:96,date:'2026-09-10',title:'すくすく赤ちゃんおはなし会（9月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'赤ちゃんと保護者のための読み聞かせイベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:97,date:'2026-09-12',title:'絵本・紙芝居を楽しむ会（9月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'絵本と紙芝居を親子で楽しむ図書館イベントです。',source:'和歌山市公式',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/1045364.html'},
  {id:98,date:'2026-09-20',title:'おたんじょうびのおはなし会（9月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'9月生まれの子どもたちをお話でお祝いするイベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:99,date:'2026-09-22',title:'親子でボードゲームをしよう！',city:'和歌山市',category:'学び・講座',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:true,unconfirmed:true,description:'ボードゲームを通じて読解力と想像力を育む親子イベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:100,date:'2026-09-24',title:'赤ちゃんおはなし会（西分館・9月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'赤ちゃんと保護者のための読み聞かせイベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:101,date:'2026-09-25',title:'みんなのおはなし会（西分館・9月）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'家族で絵本やお話を楽しめる西分館のイベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:102,date:'2026-09-27',title:'西分館上映会 ～たまごにいちゃん～',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'子ども向け作品「たまごにいちゃん」を楽しむ上映会です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:103,date:'2026-09-28',title:'ブックハンター西分館～本を手がかりにミッション攻略～',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'本をヒントに図書館のミッションへ挑戦する体験イベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:104,date:'2026-09-14',title:'おやこの座談会・相談会',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市内',free:true,kids:true,unconfirmed:true,description:'子育てプランナーと親子で話せる座談会・相談会です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:105,date:'2026-09-26',title:'小中高生の保護者のための一緒に考える塾',city:'和歌山市',category:'学び・講座',time:'日時は詳細ページを確認',place:'和歌山市民図書館 本館',free:true,kids:false,unconfirmed:true,description:'AI時代に子どもが身に付けたいスキルについて保護者と考える講座です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:106,date:'2026-09-29',title:'語りの森のむかしばなし・わらべうた（西分館）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'西分館で昔話とわらべうたを楽しむ親子イベントです。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'},
  {id:107,date:'2026-09-30',title:'おはなしだいすきよっといで！（西分館）',city:'和歌山市',category:'子育て',time:'日時は詳細ページを確認',place:'和歌山市民図書館 西分館',free:true,kids:true,unconfirmed:true,description:'西分館で絵本や物語に親しめるおはなし会です。',source:'和歌山市公式 子育てイベント',sourceUrl:'https://www.city.wakayama.wakayama.jp/kankou/event/1003235/index.html'}
];

const cities=['すべて','和歌山市','岩出市','紀の川市','海南市','有田市'];
const categories=['すべて','子育て','暮らし','お祭り','マルシェ','グルメ','商業施設','施設イベント','道の駅・市場','音楽・舞台','スポーツ','文化・芸術','学び・講座','自然・アウトドア','美容・健康','ワークショップ'];
let viewDate=new Date(2026,7,1),city='すべて',category='すべて',query='',onlyFavorites=false;
const favorites=new Set(JSON.parse(localStorage.getItem('wakayama-favorites')||'[]'));
const $=selector=>document.querySelector(selector);

function renderFilters(){
  $('#city-filters').innerHTML=cities.map(item=>`<button class="chip ${item===city?'active':''}" type="button" data-city="${item}">${item}</button>`).join('');
  $('#category-filters').innerHTML=categories.map(item=>`<button class="chip ${item===category?'active':''}" type="button" data-category="${item}">${item}</button>`).join('');
}

function render(){
  renderFilters();
  const year=viewDate.getFullYear(),month=viewDate.getMonth();
  $('#month-title').textContent=`${year}年${month+1}月`;
  const list=events.filter(event=>{
    const date=new Date(`${event.date}T00:00:00`);
    const searchText=`${event.title} ${event.city} ${event.category} ${event.place} ${event.description} ${event.source}`.toLowerCase();
    return date.getFullYear()===year&&date.getMonth()===month&&(city==='すべて'||event.city===city)&&(category==='すべて'||event.category===category)&&(!query||searchText.includes(query.toLowerCase()))&&(!onlyFavorites||favorites.has(event.id));
  }).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));
  $('#result-count').textContent=list.length;
  const weekdays=['日','月','火','水','木','金','土'];
  $('#event-list').innerHTML=list.length?list.map(event=>{
    const date=new Date(`${event.date}T00:00:00`);
    return `<article class="event-card"><div class="date-box"><span class="month">${date.getMonth()+1}月</span><strong>${date.getDate()}</strong><span class="weekday">${weekdays[date.getDay()]}曜日</span></div><div class="event-info"><div class="tags"><span class="tag city">${event.city}</span><span class="tag">${event.category}</span>${event.free?'<span class="tag free">参加無料</span>':''}${event.unconfirmed?'<span class="tag check">日時要確認</span>':''}</div><h3>${event.title}</h3><div class="event-meta"><span>◷ ${event.time}</span><span>⌖ ${event.place}</span></div></div><div class="card-actions"><button class="favorite ${favorites.has(event.id)?'active':''}" data-favorite="${event.id}" aria-label="お気に入り">${favorites.has(event.id)?'♥':'♡'}</button><button class="details" data-detail="${event.id}">詳しく見る</button></div></article>`;
  }).join(''):'<div class="empty"><h3>条件に合うイベントがありません</h3><p>条件を変えるか、別の月を見てみてください。</p></div>';
}

document.addEventListener('click',event=>{
  const button=event.target.closest('button');if(!button)return;
  if(button.dataset.city){city=button.dataset.city;render()}
  if(button.dataset.category){category=button.dataset.category;render()}
  if(button.dataset.favorite){const id=Number(button.dataset.favorite);favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('wakayama-favorites',JSON.stringify([...favorites]));render()}
  if(button.dataset.detail)openDetail(Number(button.dataset.detail));
});
$('#prev-month').onclick=()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1);render()};
$('#next-month').onclick=()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+1,1);render()};
$('#search-form').onsubmit=event=>{event.preventDefault();query=$('#search-input').value.trim();render();$('#events').scrollIntoView()};
$('#favorites-only').onchange=event=>{onlyFavorites=event.target.checked;render()};
$('#reset-filters').onclick=()=>{city='すべて';category='すべて';query='';onlyFavorites=false;$('#search-input').value='';$('#favorites-only').checked=false;render()};

function openDetail(id){
  const event=events.find(item=>item.id===id),date=new Date(`${event.date}T00:00:00`);
  const url=eventUrl(event),encoded=encodeURIComponent(url),shareText=encodeURIComponent(`${event.title}｜わかやま日和`);
  $('#dialog-content').innerHTML=`<div class="category-visual" aria-hidden="true">${categoryIcon(event.category)}</div><div class="dialog-hero"><div class="tags"><span class="tag city">${event.city}</span><span class="tag">${event.category}</span>${event.unconfirmed?'<span class="tag check">日時要確認</span>':''}</div><h2>${event.title}</h2><p>${event.description}</p></div><div class="dialog-body"><dl class="detail-grid"><dt>開催日</dt><dd>${date.getFullYear()}年${date.getMonth()+1}月${date.getDate()}日</dd><dt>時間</dt><dd>${event.time}</dd><dt>会場</dt><dd>${event.place}</dd><dt>料金</dt><dd>${event.free?'無料':'公式情報をご確認ください'}</dd><dt>情報源</dt><dd><a href="${event.sourceUrl}" target="_blank" rel="noopener noreferrer">${event.source} ↗</a></dd></dl><p class="source-note">内容が変更・中止になる場合があります。お出かけ前に公式情報をご確認ください。</p><div class="share-row"><a class="line-share" href="https://social-plugins.line.me/lineit/share?url=${encoded}" target="_blank" rel="noopener">LINEで送る</a><a class="x-share" href="https://twitter.com/intent/tweet?text=${shareText}&url=${encoded}" target="_blank" rel="noopener">Xで共有</a><button class="copy-share" type="button">URLをコピー</button></div><a class="event-page-link" href="events/event-${event.id}.html">イベント個別ページを開く →</a><div class="dialog-actions"><button class="share-button" type="button">端末の共有機能</button><a class="calendar-link" href="${calendarUrl(event)}" target="_blank" rel="noopener">カレンダーに追加</a></div></div>`;
  $('#event-dialog').showModal();$('.share-button').onclick=()=>shareEvent(event);$('.copy-share').onclick=async()=>{await navigator.clipboard.writeText(url);toast('イベントURLをコピーしました')};
}
$('.dialog-close').onclick=()=>$('#event-dialog').close();
$('#event-dialog').onclick=event=>{if(event.target===$('#event-dialog'))$('#event-dialog').close()};
function calendarUrl(event){const date=event.date.replaceAll('-','');return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.title)}&dates=${date}/${date}&location=${encodeURIComponent(event.place)}&details=${encodeURIComponent(event.description)}`}
function eventUrl(event){return new URL(`events/event-${event.id}.html`,location.href).href}
function categoryIcon(category){return ({'子育て':'👪','マルシェ':'🧺','お祭り':'🏮','グルメ':'🍊','音楽・舞台':'🎵','文化・芸術':'🎨','スポーツ':'⚽','自然・アウトドア':'🌿','ワークショップ':'✂️','商業施設':'🛍️','施設イベント':'🎪','道の駅・市場':'🥬'})[category]||'📅'}
async function shareEvent(event){const data={title:event.title,text:`${event.city}で開催：${event.title}`,url:eventUrl(event)};if(navigator.share){await navigator.share(data)}else{await navigator.clipboard.writeText(`${data.text} ${data.url}`);toast('イベント情報をコピーしました')}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
$('#post-button').onclick=()=>toast('掲載依頼フォームは次の段階で接続できます');
$('#structured-data').textContent=JSON.stringify({'@context':'https://schema.org','@graph':events.filter(event=>!event.unconfirmed).map(event=>({'@type':'Event',name:event.title,startDate:event.date,eventStatus:'https://schema.org/EventScheduled',eventAttendanceMode:'https://schema.org/OfflineEventAttendanceMode',url:eventUrl(event),location:{'@type':'Place',name:event.place,address:{'@type':'PostalAddress',addressLocality:event.city,addressRegion:'和歌山県',addressCountry:'JP'}},description:event.description,isAccessibleForFree:event.free}))});
render();
